#!/usr/bin/env python3
"""
Module: Async Comprehension

This module imports `async_generator` and defines an asynchronous
comprehension to collect and return 10 random numbers.
"""

from typing import List
from importlib import import_module as get


# Dynamically import the async_generator from the module '0-async_generator'
async_generator = get('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronously collects 10 random numbers using async comprehension
    over the `async_generator` coroutine.

    Returns:
        List[float]: A list of 10 random floats generated by `async_generator`.
    """
    return [n async for n in async_generator()]
